import * as db from './db.js';
import {dateKey,formatDate,monthCells} from './calendar.js';
import {createPerson,suggestions,categories,escapeHTML as esc} from './people.js';
import {flowerSVG,getFlowerType} from './flower.js';
import {pickComment} from './comments.js';
const app=document.querySelector('#app');let people=[],logs=[],draft=[],viewMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1,12),busy=false,noticeTimer;
const button=(text,action,cls='')=>`<button class="${cls}" data-action="${action}">${text}</button>`;
function notify(text){document.querySelector('#notice').textContent=text;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>document.querySelector('#notice').textContent='',5000);}
async function refresh(){[people,logs]=await Promise.all([db.all('people'),db.all('dailyLogs')]);people.sort((a,b)=>a.sortOrder-b.sortOrder);}
function footer(){return `<nav class="bottom"><a class="primary" href="#day/${dateKey()}">＋ 今日の会話</a><a class="settings-link" href="#settings" aria-label="設定・人物編集">⚙ <span>人物・設定</span></a></nav>`;}
function onboarding(){app.innerHTML=`<section class="intro"><div class="intro-flower">${flowerSVG(dateKey(),3,{large:true})}</div><span class="eyebrow">はじめの一歩</span><h1>よく話す人を<br>登録しましょう</h1><p>あとからいつでも追加・並び替えできます。</p><div class="choices">${suggestions.map(([name],i)=>`<button data-suggestion="${i}" aria-pressed="${draft.some(p=>p.displayName===name)}">${esc(name)}</button>`).join('')}</div><form id="onboard-add"><label for="new-name">名前を入力して追加</label><div class="input-row"><input id="new-name" name="name" maxlength="40" placeholder="例：平井さん" required>${button('追加','submit')}</div></form><div class="drafts">${draft.filter(p=>!suggestions.some(([n])=>n===p.displayName)).map(p=>`<button data-remove-draft="${p.id}">${esc(p.displayName)} ×</button>`).join('')}</div>${button('この人たちで始める','initialize','primary wide')}<p class="small">まだ登録しなくても始められます。</p><p class="privacy">会話の内容は記録しません。<br>「誰と話したか」だけを、この端末に保存します。</p></section>`;}
function calendar(){const y=viewMonth.getFullYear(),m=viewMonth.getMonth();const counts=new Map();logs.forEach(l=>counts.set(l.date,(counts.get(l.date)||0)+1));app.innerHTML=`<section class="calendar"><div class="section-top"><span class="eyebrow">日々のつながり</span><a href="#settings" class="text-link">人物・設定</a></div><h1>ひとことから、ひと花。</h1><div class="month-nav">${button('‹ <span>先月</span>','prev')}<button data-action="month" class="month-title">${y} <span>/</span> ${m+1} <small>⌄</small></button>${button('<span>来月</span> ›','next')}</div><div class="month-sub"><span>${getFlowerType(dateKey(viewMonth)).name}の月</span>${button('今月に戻る','today-month','text-link')}</div><div class="calendar-grid"><div class="week sunday">日</div>${['月','火','水','木','金','土'].map(w=>`<div class="week">${w}</div>`).join('')}${monthCells(y,m).map(date=>date?`<a class="day ${date===dateKey()?'today':''}" href="#day/${date}" aria-label="${formatDate(date)}、${counts.get(date)||0}人" ${date===dateKey()?'aria-current="date"':''}><span>${Number(date.slice(8))}</span>${counts.has(date)?flowerSVG(date,counts.get(date)):'<span class="quiet-dot" aria-hidden="true"></span>'}</a>`:'<div class="day blank"></div>').join('')}</div><div class="calendar-note"><span class="tiny-flower">${flowerSVG(dateKey(viewMonth),3)}</span><p>短い「ありがとう」も、ひとつのつながり。<br><span>日付を押すと、その日の記録を開きます。</span></p></div><details class="guide"><summary>この花カレンダーについて</summary><p>ひとりと話すと、花びらが1枚色づきます。5人で花が咲き、そのあとは色合いが少し変わります。</p><p>話さない日も、そのままで大丈夫。店員さんへの「お願いします」も記録できます。AI・テレビ・独り言は含めません。</p><p>「店員さん」などのボタンも1日1人として数えます。別の人は「店員さん（朝）」など、別々に登録してください。</p></details></section>${footer()}`;}
function currentDate(){const s=location.hash.split('/')[1];return /^\d{4}-\d{2}-\d{2}$/.test(s||'')&&dateKey(new Date(`${s}T12:00:00`))===s?s:dateKey();}
function day(){const date=currentDate();const selected=new Set(logs.filter(l=>l.date===date).map(l=>l.personId));const shown=people.filter(p=>p.isActive||selected.has(p.id));app.innerHTML=`<section class="entry"><a href="#calendar" class="back">‹ カレンダー</a><p class="date-label">${formatDate(date)}</p><h1>今日、誰としゃべった？</h1><p>話した人をタップしてください。</p><div class="people-grid">${shown.map(p=>`<button data-person="${p.id}" aria-pressed="${selected.has(p.id)}"><span class="person-check">${selected.has(p.id)?'✓':'＋'}</span><span>${esc(p.displayName)}${!p.isActive?'<small>非表示の人物</small>':''}</span></button>`).join('')}</div><a class="add-person" href="#settings">＋ 人物を追加・編集する</a><div id="flower-stage" class="flower-stage">${flowerSVG(date,selected.size,{large:true})}<p class="count">${date===dateKey()?'今日':'この日'} ${selected.size}人と話しました</p><p class="bloom-message">${selected.size>=5?'今日の花が咲きました 🌸':'ひとことのつながりを、少しずつ。'}</p></div><p class="saved">✓ タップするたびに自動保存します</p><p class="small">同じ人は、1日にひとり。もう一度押すと取り消せます。</p></section>`;}
function settings(){app.innerHTML=`<section class="settings"><a href="#calendar" class="back">‹ カレンダー</a><span class="eyebrow">あなたのつながり</span><h1>人物・設定</h1><p>よく話す人を、使いやすい順番に。</p>${button('＋ 人物を追加','add-person','primary wide')}<div class="people-list">${people.map((p,i)=>`<div class="person-row ${!p.isActive?'inactive':''}"><div><strong>${esc(p.displayName)}</strong><small>${categories[p.category]}${!p.isActive?' · 非表示':''}</small></div><div class="row-actions"><button data-move="${p.id}" data-dir="-1" aria-label="${esc(p.displayName)}を上へ" ${i===0?'disabled':''}>↑</button><button data-move="${p.id}" data-dir="1" aria-label="${esc(p.displayName)}を下へ" ${i===people.length-1?'disabled':''}>↓</button><button data-edit="${p.id}">編集</button></div></div>`).join('')}</div><div class="info-box"><h2>あなたの端末だけに保存</h2><p>保存するのは人物名・関係カテゴリ・話した日と、アプリの管理情報です。会話内容や音声、位置情報は保存しません。</p><p>ブラウザのデータを消すと記録も消えます。機種変更時の引き継ぎには、まだ対応していません。</p></div><details class="guide"><summary>ホーム画面に追加する</summary><p>iPhoneのSafariでこのアプリを開き、共有メニューから「ホーム画面に追加」を選んでください。一度読み込むとオフラインでも使えます。</p></details><p class="small">今日、誰としゃべった？ · v1.0.0</p></section>`;}
async function render(){await refresh();if(!await db.setting('initialized'))return onboarding();if(location.hash.startsWith('#day/'))day();else if(location.hash==='#settings')settings();else calendar();}
function dialog(content){const el=document.createElement('dialog');el.innerHTML=content;document.body.append(el);el.addEventListener('close',()=>el.remove());el.showModal();el.querySelector('[data-close]')?.addEventListener('click',()=>el.close());return el;}
function editPerson(id){const p=people.find(p=>p.id===id);const el=dialog(`<form id="person-form"><h2>${p?'人物を編集':'人物を追加'}</h2><label for="person-name">名前</label><input id="person-name" name="name" value="${esc(p?.displayName||'')}" maxlength="40" required><label for="category">関係カテゴリ</label><select name="category" id="category">${Object.entries(categories).map(([k,v])=>`<option value="${k}" ${(p?.category||'other')===k?'selected':''}>${v}</option>`).join('')}</select>${p?`<label class="check-label"><input name="active" type="checkbox" ${p.isActive?'checked':''}> 入力画面に表示する</label><p class="small">非表示にしても、過去の花と記録は残ります。削除の代わりに非表示を使います。</p>`:''}<div class="dialog-actions"><button type="button" data-close>戻る</button><button class="primary" type="submit">保存</button></div><p role="status" class="form-status"></p></form>`);el.querySelector('form').onsubmit=async e=>{e.preventDefault();const form=new FormData(e.target);const name=form.get('name').trim();if(!name)return;const submit=e.target.querySelector('[type=submit]');submit.disabled=true;try{await db.put('people',p?{...p,displayName:name,category:form.get('category'),isActive:form.has('active')}:createPerson(name,form.get('category'),people.length));el.close();await render();notify('人物を保存しました');}catch{el.querySelector('.form-status').textContent='保存できませんでした。もう一度お試しください。';submit.disabled=false;}};}
app.addEventListener('submit',async e=>{if(e.target.id!=='onboard-add')return;e.preventDefault();const input=e.target.elements.name;const name=input.value.trim();if(!name)return;if(!draft.some(p=>p.displayName===name))draft.push(createPerson(name,'other',draft.length));onboarding();});
app.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||busy)return;try{if(b.dataset.suggestion!==undefined){const [name,cat]=suggestions[Number(b.dataset.suggestion)];const found=draft.find(p=>p.displayName===name);draft=found?draft.filter(p=>p!==found):[...draft,createPerson(name,cat,draft.length)];onboarding();return;}if(b.dataset.removeDraft){draft=draft.filter(p=>p.id!==b.dataset.removeDraft);onboarding();return;}if(b.dataset.person){busy=true;const date=currentDate();const previous=logs.filter(l=>l.personId===b.dataset.person);const added=await db.toggleTalk(date,b.dataset.person);await refresh();day();const replacement=app.querySelector(`[data-person="${b.dataset.person}"]`);replacement?.focus({preventScroll:true});if(added){notify(pickComment(previous,date));app.querySelector('.flower-stage .flower')?.classList.add('bloom');}else notify('この日の選択を取り消しました');return;}if(b.dataset.edit)return editPerson(b.dataset.edit);if(b.dataset.move){busy=true;const index=people.findIndex(p=>p.id===b.dataset.move),next=index+Number(b.dataset.dir);if(next>=0&&next<people.length){[people[index],people[next]]=[people[next],people[index]];await db.reorder(people);await render();}return;}switch(b.dataset.action){case 'initialize':busy=true;await db.initialize(draft.map((p,i)=>({...p,sortOrder:i})));location.hash='#calendar';await render();break;case 'prev':viewMonth.setMonth(viewMonth.getMonth()-1);calendar();break;case 'next':viewMonth.setMonth(viewMonth.getMonth()+1);calendar();break;case 'today-month':viewMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1,12);calendar();break;case 'add-person':editPerson();break;case 'month':{const el=dialog(`<form><h2>表示する年月</h2><label for="year">年</label><input id="year" name="year" type="number" min="1900" max="2200" value="${viewMonth.getFullYear()}" required><label for="month">月</label><select id="month" name="month">${Array.from({length:12},(_,i)=>`<option value="${i}" ${i===viewMonth.getMonth()?'selected':''}>${i+1}月</option>`).join('')}</select><div class="dialog-actions"><button type="button" data-close>戻る</button><button class="primary">表示</button></div></form>`);el.querySelector('form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);viewMonth=new Date(Number(f.get('year')),Number(f.get('month')),1,12);el.close();calendar();};break;}}}catch(error){notify('保存・読み込みができませんでした。もう一度お試しください。');console.error(error);}finally{busy=false;}});
window.addEventListener('hashchange',()=>render().catch(()=>notify('記録を読み込めませんでした')));
window.addEventListener('pageshow',()=>{if(!busy)render().catch(()=>{});});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&!busy)render().catch(()=>{});});
render().catch(()=>{app.innerHTML='<section><h1>記録を開けませんでした</h1><p>ブラウザの保存領域を確認し、再読み込みしてください。</p><button onclick="location.reload()">再読み込み</button></section>';});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>notify('オフラインの準備ができませんでした。オンラインで開き直してください。'));
